name: External

on:
  push:
    branches:
      - main  # Trigger this on push to the 'main' branch

jobs:
  run-script:
    runs-on: windows-latest  # Specifies Windows environment for the job

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2  # Fetches your repository

      - name: Set up Python
        uses: actions/setup-python@v2  # Sets up Python for the job
        with:
          python-version: '3.x'  # Use a version like 3.x or 3.9
          
      - name: Set EXTERNAL_LINK and Run Python script
        run: |
          echo "EXTERNAL_LINK=${{ secrets.EXTERNAL_LINK }}" >> $GITHUB_ENV  # Set the EXTERNAL_LINK secret as an environment variable
          python External.py  # Run the main script
        env:
          EXTERNAL_LINK: ${{ secrets.EXTERNAL_LINK }}  # Inject the EXTERNAL_LINK secret as an environment variable
